// apps/web/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import {
    addMonths,
    eachDayOfInterval,
    endOfMonth,
    format,
    isWithinInterval,
    parseISO,
    startOfMonth,
    subMonths,
  } from "date-fns";
  import { AlertTriangle, ArrowLeft, ArrowRight, CalendarDays, Check, Plus, Search, Sparkles, X } from "@lucide/svelte";
  import type { CalendarComparison, CalendarEvent, School } from "@commondays/shared";

  const academicYear = "2026-27";
  const weekdays = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"];

  let comparison: CalendarComparison | null = null;
  let allSchools: School[] = [];
  let selectedIds = ["uiuc", "berkeley", "nyu"];
  let activeMonth = new Date(2026, 11, 1);
  let selectedDate = new Date(2026, 11, 23);
  let isLoading = true;
  let error = "";
  let schoolPickerOpen = false;
  let reportOpen = false;
  let reportSchool: School | null = null;
  let reportDetails = "";
  let reportStatus = "";
  let query = "";

  $: selectedSchools = allSchools.filter((school) => selectedIds.includes(school.id));
  $: searchResults = allSchools.filter((school) => {
    if (selectedIds.includes(school.id)) return false;
    return `${school.name} ${school.shortName} ${school.location}`.toLowerCase().includes(query.toLowerCase());
  });
  $: monthStart = startOfMonth(activeMonth);
  $: monthDays = eachDayOfInterval({ start: monthStart, end: endOfMonth(activeMonth) });
  $: leadingDays = Array(monthStart.getDay()).fill(null);
  $: bestWindow = findBestWindow(comparison?.events ?? [], selectedIds);

  onMount(async () => {
    try {
      const schoolResponse = await fetch("/api/v1/schools");
      if (!schoolResponse.ok) throw new Error("School library unavailable");
      const schoolBody = (await schoolResponse.json()) as { schools: School[] };
      allSchools = schoolBody.schools;
      await loadComparison();
    } catch (cause) {
      error = cause instanceof Error ? cause.message : "Could not load Common Days";
    } finally {
      isLoading = false;
    }
  });

  async function loadComparison() {
    const params = new URLSearchParams({ year: academicYear, schools: selectedIds.join(",") });
    const response = await fetch(`/api/v1/calendars?${params}`);
    if (!response.ok) throw new Error("Calendar comparison unavailable");
    comparison = (await response.json()) as CalendarComparison;
  }

  async function addSchool(id: string) {
    selectedIds = [...selectedIds, id];
    schoolPickerOpen = false;
    query = "";
    await loadComparison();
  }

  async function removeSchool(id: string) {
    if (selectedIds.length === 1) return;
    selectedIds = selectedIds.filter((schoolId) => schoolId !== id);
    await loadComparison();
  }

  function eventsForDate(date: Date) {
    return (comparison?.events ?? []).filter((event) =>
      isWithinInterval(date, { start: parseISO(event.startDate), end: parseISO(event.endDate) }),
    );
  }

  function schoolIsOff(schoolId: string, date: Date) {
    return eventsForDate(date).some((event) => event.schoolId === schoolId);
  }

  function everyoneIsOff(date: Date) {
    return selectedIds.length > 0 && selectedIds.every((id) => schoolIsOff(id, date));
  }

  function openReport(school: School) {
    reportSchool = school;
    reportDetails = "";
    reportStatus = "";
    reportOpen = true;
  }

  async function submitReport() {
    if (!reportSchool || reportDetails.trim().length < 10) return;
    const response = await fetch("/api/v1/reports", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        schoolId: reportSchool.id,
        academicYear,
        reason: "other",
        details: reportDetails,
      }),
    });
    reportStatus = response.ok ? "Report submitted for review." : "That report could not be submitted.";
  }

  function findBestWindow(events: CalendarEvent[], schoolIds: string[]) {
    if (!events.length || !schoolIds.length) return null;
    const dates = eachDayOfInterval({ start: new Date(2026, 7, 1), end: new Date(2027, 8, 1) });
    let best: Date[] = [];
    let current: Date[] = [];

    for (const date of dates) {
      const off = schoolIds.every((id) =>
        events.some((event) => event.schoolId === id && isWithinInterval(date, {
          start: parseISO(event.startDate),
          end: parseISO(event.endDate),
        })),
      );
      if (off) {
        current = [...current, date];
        if (current.length > best.length) best = current;
      } else {
        current = [];
      }
    }

    return best.length ? { start: best[0], end: best[best.length - 1], days: best.length } : null;
  }
</script>

<svelte:head>
  <title>Common Days | Find the break everyone shares</title>
</svelte:head>

<main>
  <header class="site-header">
    <a class="brand" href="/" aria-label="Common Days home">
      <span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span>
      <span>COMMON DAYS</span>
    </a>
    <div class="header-status"><span></span> Building the shared calendar library</div>
  </header>

  <section class="intro" aria-labelledby="page-title">
    <div>
      <span class="eyebrow">ACADEMIC CALENDAR COMPARISON</span>
      <h1 id="page-title">Find the days<br /><em>everyone shares.</em></h1>
    </div>
    <div class="intro-copy">
      <p>Add each friend&apos;s school. Common Days lines up their official academic calendars and marks the exact dates everyone is free.</p>
      <div class="library-note"><Sparkles size={18} /><span>One upload makes a school year reusable for everyone.</span></div>
    </div>
  </section>

  <section class="product-shell" aria-label="Common Days calendar application">
    <div class="window-bar">
      <div class="window-dots" aria-hidden="true"><i></i><i></i><i></i></div>
      <span>commondays.app/groups/summer-plans</span>
      <b>DEVELOPMENT DATA</b>
    </div>

    {#if isLoading}
      <div class="state-panel"><Sparkles class="spin" size={24} /> Loading the school library...</div>
    {:else if error}
      <div class="state-panel error"><AlertTriangle size={24} /> {error}. Make sure the API is running.</div>
    {:else}
      <div class="app-grid">
        <aside class="sidebar">
          <div class="group-heading">
            <div><span>YOUR GROUP</span><h2>Summer plans</h2></div>
            <button class="round-button" aria-label="Add a school" onclick={() => (schoolPickerOpen = true)}><Plus size={19} /></button>
          </div>

          <div class="friend-row" aria-label="Four friends in this group">
            <i>NV</i><i>MJ</i><i>SK</i><i>+</i><span>4 friends</span>
          </div>

          <div class="school-list">
            {#each selectedSchools as school (school.id)}
              <article class="school-card">
                <span class="school-avatar" style:background={school.color}>{school.initials}</span>
                <div><strong>{school.shortName}</strong><small>{academicYear} · Available</small></div>
                <div class="school-actions">
                  <button onclick={() => openReport(school)}>Report</button>
                  <button aria-label={`Remove ${school.shortName}`} onclick={() => removeSchool(school.id)}><X size={13} /></button>
                </div>
              </article>
            {/each}
          </div>

          <button class="add-school" onclick={() => (schoolPickerOpen = true)}><Plus size={17} /> Add another school</button>

          <div class="share-card">
            <span><Sparkles size={18} /></span>
            <strong>Bring your friends in</strong>
            <p>Everyone can use the same group comparison.</p>
            <button>Copy group link</button>
          </div>
        </aside>

        <section class="calendar-panel">
          <div class="calendar-title">
            <div><span>ACADEMIC YEAR {academicYear}</span><h2>When is everyone free?</h2></div>
            <button class="secondary-button"><CalendarDays size={16} /> Year overview</button>
          </div>

          {#if bestWindow}
            <button class="best-window" onclick={() => { activeMonth = startOfMonth(bestWindow!.start); selectedDate = bestWindow!.start; }}>
              <span class="best-icon"><Sparkles size={22} /></span>
              <span><small>BEST SHARED WINDOW</small><strong>{format(bestWindow.start, "MMM d")} - {format(bestWindow.end, "MMM d")}</strong></span>
              <span class="best-days"><b>{bestWindow.days}</b><small>days together</small></span>
              <span>Show on calendar <ArrowRight size={15} /></span>
            </button>
          {/if}

          <div class="month-nav">
            <button aria-label="Previous month" onclick={() => (activeMonth = subMonths(activeMonth, 1))}><ArrowLeft size={18} /></button>
            <div><span>MONTH VIEW</span><strong>{format(activeMonth, "MMMM yyyy")}</strong></div>
            <button aria-label="Next month" onclick={() => (activeMonth = addMonths(activeMonth, 1))}><ArrowRight size={18} /></button>
          </div>

          <div class="calendar-wrap">
            <div class="weekday-row">{#each weekdays as day}<span>{day}</span>{/each}</div>
            <div class="month-grid">
              {#each leadingDays as _}<div class="empty-day" aria-hidden="true"></div>{/each}
              {#each monthDays as date}
                <button
                  class:everyone-off={everyoneIsOff(date)}
                  class:selected={format(date, "yyyy-MM-dd") === format(selectedDate, "yyyy-MM-dd")}
                  class="day-cell"
                  aria-label={format(date, "EEEE, MMMM d, yyyy")}
                  onclick={() => (selectedDate = date)}
                >
                  <span class="day-number">{format(date, "d")}</span>
                  {#if everyoneIsOff(date)}<span class="everyone-label"><Check size={10} /> ALL FREE</span>{/if}
                  <span class="school-lines" aria-hidden="true">
                    {#each selectedSchools as school}
                      <i class:off={schoolIsOff(school.id, date)} style:--school-color={school.color}><b>{school.initials}</b><span></span></i>
                    {/each}
                  </span>
                </button>
              {/each}
            </div>
          </div>

          <div class="date-detail">
            <div><span>SELECTED DATE</span><strong>{format(selectedDate, "EEEE, MMMM d")}</strong></div>
            <div class="detail-schools">
              {#each selectedSchools as school}
                <span class:off={schoolIsOff(school.id, selectedDate)} style:--school-color={school.color}>
                  <i></i>{school.shortName}<b>{schoolIsOff(school.id, selectedDate) ? "No classes" : "Classes"}</b>
                </span>
              {/each}
            </div>
          </div>
        </section>
      </div>
    {/if}
  </section>
</main>

{#if schoolPickerOpen}
  <div class="modal-backdrop" role="presentation" onclick={(event) => event.target === event.currentTarget && (schoolPickerOpen = false)}>
    <div class="modal" role="dialog" aria-modal="true" aria-labelledby="school-picker-title" tabindex="-1">
      <button class="modal-close" aria-label="Close" onclick={() => (schoolPickerOpen = false)}><X size={18} /></button>
      <span class="modal-kicker">ADD TO YOUR GROUP</span>
      <h2 id="school-picker-title">What school are we adding?</h2>
      <label class="search-box"><Search size={18} /><input bind:value={query} placeholder="Search a college or university" /></label>
      <div class="search-results">
        {#each searchResults as school}
          <button onclick={() => addSchool(school.id)}>
            <span class="school-avatar" style:background={school.color}>{school.initials}</span>
            <span><strong>{school.name}</strong><small>{school.location} · {academicYear} available</small></span>
            <Plus size={18} />
          </button>
        {:else}
          <p>No other matching schools yet. Uploading a missing calendar comes next.</p>
        {/each}
      </div>
    </div>
  </div>
{/if}

{#if reportOpen && reportSchool}
  <div class="modal-backdrop" role="presentation" onclick={(event) => event.target === event.currentTarget && (reportOpen = false)}>
    <div class="modal report-modal" role="dialog" aria-modal="true" aria-labelledby="report-title" tabindex="-1">
      <button class="modal-close" aria-label="Close" onclick={() => (reportOpen = false)}><X size={18} /></button>
      <span class="modal-kicker">CALENDAR CORRECTION</span>
      <h2 id="report-title">Report a problem with {reportSchool.shortName}</h2>
      <p>Tell us which date is wrong or missing. A report proposes a correction and never overwrites the shared calendar automatically.</p>
      <textarea bind:value={reportDetails} rows="5" placeholder="Example: Spring break should end on March 21, not March 20."></textarea>
      <button class="primary-button" disabled={reportDetails.trim().length < 10} onclick={submitReport}>Submit report</button>
      {#if reportStatus}<div class="report-status"><Check size={16} /> {reportStatus}</div>{/if}
    </div>
  </div>
{/if}

// app/page.tsx
"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type BreakEvent = {
  id: string;
  title: string;
  start: string;
  end: string;
  kind: "break" | "holiday" | "summer";
};

type School = {
  id: string;
  name: string;
  shortName: string;
  location: string;
  initials: string;
  color: string;
  available: boolean;
  breaks: BreakEvent[];
};

type ViewMode = "year" | "winter" | "spring";
type AddStage = "search" | "available" | "missing" | "extracting" | "review" | "published";

const DAY = 86_400_000;

const demoSchools: School[] = [
  {
    id: "uiuc",
    name: "University of Illinois Urbana-Champaign",
    shortName: "UIUC",
    location: "Urbana-Champaign, IL",
    initials: "IL",
    color: "#5968f2",
    available: true,
    breaks: [
      { id: "uiuc-fall", title: "Fall break", start: "2026-11-21", end: "2026-11-29", kind: "break" },
      { id: "uiuc-winter", title: "Winter break", start: "2026-12-19", end: "2027-01-17", kind: "break" },
      { id: "uiuc-spring", title: "Spring break", start: "2027-03-13", end: "2027-03-21", kind: "break" },
      { id: "uiuc-summer", title: "Summer", start: "2027-05-14", end: "2027-07-31", kind: "summer" },
    ],
  },
  {
    id: "berkeley",
    name: "University of California, Berkeley",
    shortName: "UC Berkeley",
    location: "Berkeley, CA",
    initials: "CA",
    color: "#ff735f",
    available: true,
    breaks: [
      { id: "cal-fall", title: "Thanksgiving", start: "2026-11-25", end: "2026-11-29", kind: "holiday" },
      { id: "cal-winter", title: "Winter break", start: "2026-12-12", end: "2027-01-18", kind: "break" },
      { id: "cal-spring", title: "Spring break", start: "2027-03-20", end: "2027-03-28", kind: "break" },
      { id: "cal-summer", title: "Summer", start: "2027-05-15", end: "2027-07-31", kind: "summer" },
    ],
  },
  {
    id: "nyu",
    name: "New York University",
    shortName: "NYU",
    location: "New York, NY",
    initials: "NY",
    color: "#1fae9e",
    available: true,
    breaks: [
      { id: "nyu-fall", title: "Thanksgiving", start: "2026-11-25", end: "2026-11-29", kind: "holiday" },
      { id: "nyu-winter", title: "Winter break", start: "2026-12-22", end: "2027-01-24", kind: "break" },
      { id: "nyu-spring", title: "Spring break", start: "2027-03-13", end: "2027-03-21", kind: "break" },
      { id: "nyu-summer", title: "Summer", start: "2027-05-12", end: "2027-07-31", kind: "summer" },
    ],
  },
  {
    id: "gatech",
    name: "Georgia Institute of Technology",
    shortName: "Georgia Tech",
    location: "Atlanta, GA",
    initials: "GT",
    color: "#e8a22b",
    available: true,
    breaks: [
      { id: "gt-fall", title: "Thanksgiving", start: "2026-11-25", end: "2026-11-29", kind: "holiday" },
      { id: "gt-winter", title: "Winter break", start: "2026-12-12", end: "2027-01-10", kind: "break" },
      { id: "gt-spring", title: "Spring break", start: "2027-03-20", end: "2027-03-28", kind: "break" },
      { id: "gt-summer", title: "Summer", start: "2027-05-08", end: "2027-07-31", kind: "summer" },
    ],
  },
  {
    id: "rice",
    name: "Rice University",
    shortName: "Rice",
    location: "Houston, TX",
    initials: "RU",
    color: "#9a62df",
    available: false,
    breaks: [],
  },
  {
    id: "northeastern",
    name: "Northeastern University",
    shortName: "Northeastern",
    location: "Boston, MA",
    initials: "NE",
    color: "#e35770",
    available: false,
    breaks: [],
  },
];

const riceDraft: BreakEvent[] = [
  { id: "rice-fall", title: "Thanksgiving recess", start: "2026-11-25", end: "2026-11-29", kind: "holiday" },
  { id: "rice-winter", title: "Winter recess", start: "2026-12-17", end: "2027-01-10", kind: "break" },
  { id: "rice-spring", title: "Spring recess", start: "2027-03-13", end: "2027-03-21", kind: "break" },
  { id: "rice-summer", title: "Summer", start: "2027-05-01", end: "2027-07-31", kind: "summer" },
];

const views: Record<ViewMode, { start: string; end: string; months: string[] }> = {
  year: {
    start: "2026-08-01",
    end: "2027-07-31",
    months: ["Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
  },
  winter: {
    start: "2026-11-01",
    end: "2027-02-28",
    months: ["Nov", "Dec", "Jan", "Feb"],
  },
  spring: {
    start: "2027-02-01",
    end: "2027-05-31",
    months: ["Feb", "Mar", "Apr", "May"],
  },
};

function utc(iso: string) {
  return Date.parse(`${iso}T00:00:00Z`);
}

function formatDay(iso: string) {
  return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(utc(iso)));
}

function daysBetween(start: string, end: string) {
  return Math.round((utc(end) - utc(start)) / DAY) + 1;
}

function getCommonBreaks(schools: School[], start: string, end: string): BreakEvent[] {
  if (schools.length < 2) return [];
  const startMs = utc(start);
  const endMs = utc(end);
  const commonDays: number[] = [];

  for (let day = startMs; day <= endMs; day += DAY) {
    const everyoneFree = schools.every((school) =>
      school.breaks.some((event) => day >= utc(event.start) && day <= utc(event.end)),
    );
    if (everyoneFree) commonDays.push(day);
  }

  const segments: BreakEvent[] = [];
  let segmentStart: number | null = null;
  let previous: number | null = null;

  commonDays.forEach((day, index) => {
    if (segmentStart === null) segmentStart = day;
    if (previous !== null && day - previous > DAY) {
      segments.push({
        id: `common-${segmentStart}`,
        title: "Everyone is free",
        start: new Date(segmentStart).toISOString().slice(0, 10),
        end: new Date(previous).toISOString().slice(0, 10),
        kind: "break",
      });
      segmentStart = day;
    }
    previous = day;
    if (index === commonDays.length - 1 && segmentStart !== null) {
      segments.push({
        id: `common-${segmentStart}`,
        title: "Everyone is free",
        start: new Date(segmentStart).toISOString().slice(0, 10),
        end: new Date(day).toISOString().slice(0, 10),
        kind: "break",
      });
    }
  });

  return segments;
}

function barStyle(event: BreakEvent, view: (typeof views)[ViewMode]) {
  const rangeStart = utc(view.start);
  const rangeEnd = utc(view.end) + DAY;
  const eventStart = Math.max(utc(event.start), rangeStart);
  const eventEnd = Math.min(utc(event.end) + DAY, rangeEnd);
  if (eventStart >= rangeEnd || eventEnd <= rangeStart) return null;
  return {
    left: `${((eventStart - rangeStart) / (rangeEnd - rangeStart)) * 100}%`,
    width: `${Math.max(((eventEnd - eventStart) / (rangeEnd - rangeStart)) * 100, 0.8)}%`,
  };
}

function TimelineBar({ event, view, common = false }: { event: BreakEvent; view: (typeof views)[ViewMode]; common?: boolean }) {
  const style = barStyle(event, view);
  if (!style) return null;
  const wideEnough = parseFloat(style.width) > 10;
  return (
    <div
      className={`timeline-bar ${common ? "common-bar" : ""} ${event.kind === "summer" ? "summer-bar" : ""}`}
      style={style}
      title={`${event.title}: ${formatDay(event.start)}–${formatDay(event.end)}`}
    >
      {wideEnough ? <span>{common ? `${daysBetween(event.start, event.end)} days` : event.title}</span> : null}
    </div>
  );
}

function Mark() {
  return (
    <span className="brand-mark" aria-hidden="true">
      <i />
      <i />
      <i />
    </span>
  );
}

export default function Home() {
  const [schools, setSchools] = useState(demoSchools);
  const [selectedIds, setSelectedIds] = useState(["uiuc", "berkeley", "nyu"]);
  const [viewMode, setViewMode] = useState<ViewMode>("year");
  const [addOpen, setAddOpen] = useState(false);
  const [stage, setStage] = useState<AddStage>("search");
  const [query, setQuery] = useState("");
  const [candidateId, setCandidateId] = useState<string | null>(null);
  const [draftEvents, setDraftEvents] = useState(riceDraft);
  const [copied, setCopied] = useState(false);
  const searchRef = useRef<HTMLInputElement>(null);

  const selectedSchools = useMemo(
    () => selectedIds.map((id) => schools.find((school) => school.id === id)).filter(Boolean) as School[],
    [schools, selectedIds],
  );
  const view = views[viewMode];
  const commonBreaks = useMemo(
    () => getCommonBreaks(selectedSchools, view.start, view.end),
    [selectedSchools, view.start, view.end],
  );
  const bestBreak = useMemo(
    () => [...commonBreaks].sort((a, b) => daysBetween(b.start, b.end) - daysBetween(a.start, a.end))[0],
    [commonBreaks],
  );
  const candidate = schools.find((school) => school.id === candidateId) ?? null;
  const searchResults = schools.filter((school) => {
    const haystack = `${school.name} ${school.shortName} ${school.location}`.toLowerCase();
    return haystack.includes(query.toLowerCase()) && !selectedIds.includes(school.id);
  });

  useEffect(() => {
    if (addOpen && stage === "search") window.setTimeout(() => searchRef.current?.focus(), 80);
  }, [addOpen, stage]);

  useEffect(() => {
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") closeModal();
    };
    window.addEventListener("keydown", closeOnEscape);
    return () => window.removeEventListener("keydown", closeOnEscape);
  }, []);

  function openAdd() {
    setQuery("");
    setCandidateId(null);
    setStage("search");
    setAddOpen(true);
  }

  function closeModal() {
    setAddOpen(false);
    setStage("search");
    setCandidateId(null);
  }

  function chooseSchool(school: School) {
    setCandidateId(school.id);
    setStage(school.available ? "available" : "missing");
  }

  function addAvailableSchool() {
    if (!candidate) return;
    setSelectedIds((ids) => (ids.includes(candidate.id) ? ids : [...ids, candidate.id]));
    closeModal();
  }

  function simulateUpload() {
    setStage("extracting");
    window.setTimeout(() => setStage("review"), 1100);
  }

  function updateDraft(id: string, field: "title" | "start" | "end", value: string) {
    setDraftEvents((events) => events.map((event) => (event.id === id ? { ...event, [field]: value } : event)));
  }

  function publishDraft() {
    if (!candidate) return;
    setSchools((current) =>
      current.map((school) => (school.id === candidate.id ? { ...school, available: true, breaks: draftEvents } : school)),
    );
    setSelectedIds((ids) => (ids.includes(candidate.id) ? ids : [...ids, candidate.id]));
    setStage("published");
  }

  function removeSchool(id: string) {
    setSelectedIds((ids) => ids.filter((schoolId) => schoolId !== id));
  }

  function copyLink() {
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1600);
  }

  return (
    <main>
      <header className="site-header">
        <a className="brand" href="#top" aria-label="Common Days home">
          <Mark />
          <span>COMMON DAYS</span>
        </a>
        <nav aria-label="Primary navigation">
          <a href="#planner">Demo</a>
          <a href="#how-it-works">How it works</a>
        </nav>
        <button className="header-button" onClick={openAdd}>Add a school <span>＋</span></button>
      </header>

      <section className="hero" id="top">
        <div className="hero-copy">
          <div className="eyebrow"><span>●</span> Proof of concept · sample dates</div>
          <h1>Find the break<br />everyone <em>actually</em> shares.</h1>
          <p>
            Pick your friends&apos; schools. We&apos;ll stack their academic calendars and show the days that line up—without making the next UIUC student upload the same calendar again.
          </p>
          <div className="hero-actions">
            <button className="primary-button" onClick={() => document.getElementById("planner")?.scrollIntoView({ behavior: "smooth" })}>
              Explore the demo <span>↓</span>
            </button>
            <button className="text-button" onClick={() => { openAdd(); setQuery("Rice"); }}>
              Try a missing school <span>↗</span>
            </button>
          </div>
        </div>
        <div className="hero-visual" aria-hidden="true">
          <div className="orbit orbit-one" />
          <div className="orbit orbit-two" />
          <div className="mini-calendar">
            <div className="mini-top"><span>DEC 2026</span><b>3 schools</b></div>
            <div className="mini-dates"><span>18</span><span>19</span><span>20</span><span>21</span><strong>22</strong><strong>23</strong><strong>24</strong><span>25</span></div>
            <div className="mini-row"><i style={{ background: "#5968f2", width: "88%" }} /></div>
            <div className="mini-row"><i style={{ background: "#ff735f", width: "79%", marginLeft: "9%" }} /></div>
            <div className="mini-row"><i style={{ background: "#1fae9e", width: "70%", marginLeft: "18%" }} /></div>
            <div className="mini-highlight"><span>ALL FREE</span><b>27 DAYS</b></div>
          </div>
          <div className="hero-note note-one"><span>✓</span> UIUC calendar already here</div>
          <div className="hero-note note-two"><span>3</span> calendars compared</div>
        </div>
      </section>

      <section className="planner-section" id="planner">
        <div className="section-heading">
          <div>
            <span className="section-number">01</span>
            <p>LIVE PROTOTYPE</p>
          </div>
          <h2>Your group&apos;s calendar,<br />finally in one place.</h2>
          <p className="section-note">Click around. Remove a school, add Georgia Tech, or try Rice to see the missing-calendar flow.</p>
        </div>

        <div className="app-window">
          <div className="app-toolbar">
            <div className="window-dots"><i /><i /><i /></div>
            <div className="demo-address"><span>⌕</span> commondays.app/group/summer-plans</div>
            <div className="sample-pill">SAMPLE DATA</div>
          </div>

          <div className="app-body">
            <aside className="school-panel">
              <div className="panel-heading">
                <div>
                  <span className="tiny-label">YOUR GROUP</span>
                  <h3>Summer plans</h3>
                </div>
                <button className="icon-button" onClick={openAdd} aria-label="Add another school">＋</button>
              </div>

              <div className="people-row" aria-label="Four group members">
                <span className="person person-a">NV</span>
                <span className="person person-b">MJ</span>
                <span className="person person-c">SK</span>
                <span className="person person-d">＋</span>
                <small>4 friends</small>
              </div>

              <div className="school-list">
                {selectedSchools.map((school) => (
                  <div className="school-card" key={school.id}>
                    <span className="school-avatar" style={{ background: school.color }}>{school.initials}</span>
                    <span className="school-copy"><strong>{school.shortName}</strong><small>2026–27 · Available</small></span>
                    <button onClick={() => removeSchool(school.id)} aria-label={`Remove ${school.shortName}`}>×</button>
                  </div>
                ))}
              </div>

              <button className="add-school-button" onClick={openAdd}><span>＋</span> Add another school</button>

              <div className="share-card">
                <span className="share-spark">✦</span>
                <strong>Bring your friends in</strong>
                <p>They can see this comparison without uploading anything.</p>
                <button onClick={copyLink}>{copied ? "Copied!" : "Copy group link"}</button>
              </div>
            </aside>

            <div className="calendar-panel">
              <div className="calendar-header">
                <div>
                  <span className="tiny-label">ACADEMIC YEAR 2026–27</span>
                  <h3>When is everyone free?</h3>
                </div>
                <div className="view-switcher" aria-label="Calendar range">
                  {(["year", "winter", "spring"] as ViewMode[]).map((mode) => (
                    <button key={mode} className={viewMode === mode ? "active" : ""} onClick={() => setViewMode(mode)}>
                      {mode === "year" ? "Full year" : mode[0].toUpperCase() + mode.slice(1)}
                    </button>
                  ))}
                </div>
              </div>

              {bestBreak ? (
                <div className="best-window">
                  <div className="best-icon"><span>✦</span></div>
                  <div>
                    <span>BEST SHARED WINDOW</span>
                    <strong>{formatDay(bestBreak.start)} – {formatDay(bestBreak.end)}</strong>
                  </div>
                  <div className="best-count"><b>{daysBetween(bestBreak.start, bestBreak.end)}</b><span>days together</span></div>
                  <button onClick={copyLink}>{copied ? "Link copied" : "Plan something →"}</button>
                </div>
              ) : (
                <div className="best-window empty-window"><div><span>NO SHARED WINDOW YET</span><strong>Try removing one school</strong></div></div>
              )}

              <div className="timeline-shell">
                <div className="timeline-labels timeline-months-label"><span>School</span></div>
                <div className="timeline-months" style={{ gridTemplateColumns: `repeat(${view.months.length}, minmax(76px, 1fr))` }}>
                  {view.months.map((month) => <span key={month}>{month}</span>)}
                </div>

                <div className="timeline-scroll">
                  <div className="timeline-grid" style={{ minWidth: `${view.months.length * 76}px` }}>
                    <div className="month-lines" style={{ gridTemplateColumns: `repeat(${view.months.length}, 1fr)` }}>
                      {view.months.map((month) => <i key={month} />)}
                    </div>

                    <div className="timeline-row common-row">
                      <div className="timeline-name"><span className="all-dot">✦</span><strong>Everyone</strong></div>
                      <div className="timeline-track">
                        {commonBreaks.map((event) => <TimelineBar key={event.id} event={event} view={view} common />)}
                      </div>
                    </div>

                    {selectedSchools.map((school) => (
                      <div className="timeline-row" key={school.id}>
                        <div className="timeline-name"><span style={{ background: school.color }}>{school.initials}</span><strong>{school.shortName}</strong></div>
                        <div className="timeline-track" style={{ "--school-color": school.color } as React.CSSProperties}>
                          {school.breaks.map((event) => <TimelineBar key={event.id} event={event} view={view} />)}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              <div className="calendar-legend">
                <span><i className="legend-common" /> Everyone is free</span>
                <span><i className="legend-break" /> School break</span>
                <span className="demo-warning">Demo dates—not official school data</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="how-section" id="how-it-works">
        <div className="how-heading">
          <span className="section-number">02</span>
          <h2>Upload once.<br />Useful for everyone.</h2>
        </div>
        <div className="how-grid">
          <article>
            <span className="step-badge">1</span>
            <div className="step-visual search-visual"><span>⌕</span><p>UIUC</p><b>AVAILABLE</b></div>
            <h3>Check before uploading</h3>
            <p>Choose a school, calendar type, and year. If it already exists, use it instantly.</p>
          </article>
          <article>
            <span className="step-badge">2</span>
            <div className="step-visual upload-visual"><span>↑</span><p>academic-calendar.pdf</p><b>4 BREAKS FOUND</b></div>
            <h3>Fill the gap once</h3>
            <p>If it&apos;s missing, one person uploads and confirms the extracted dates.</p>
          </article>
          <article>
            <span className="step-badge">3</span>
            <div className="step-visual reuse-visual"><span>✓</span><p>Published for 2026–27</p><b>READY TO REUSE</b></div>
            <h3>Share the canonical version</h3>
            <p>Future students attach the reviewed calendar instead of creating another copy.</p>
          </article>
        </div>
      </section>

      <footer>
        <a className="brand footer-brand" href="#top"><Mark /><span>COMMON DAYS</span></a>
        <p>A proof of concept for finding time together.</p>
        <button onClick={() => document.getElementById("planner")?.scrollIntoView({ behavior: "smooth" })}>Back to demo ↑</button>
      </footer>

      {addOpen ? (
        <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) closeModal(); }}>
          <section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title">
            <div className="modal-top">
              <div className="modal-progress" aria-label="Add school progress">
                <i className={stage !== "search" ? "done" : "active"}>1</i><span />
                <i className={["review", "published"].includes(stage) ? "done" : ["missing", "extracting"].includes(stage) ? "active" : ""}>2</i><span />
                <i className={stage === "published" ? "done" : stage === "review" ? "active" : ""}>3</i>
              </div>
              <button className="modal-close" onClick={closeModal} aria-label="Close dialog">×</button>
            </div>

            {stage === "search" ? (
              <div className="modal-content search-stage">
                <span className="modal-kicker">STEP 1 OF 3</span>
                <h2 id="modal-title">What school are we adding?</h2>
                <p>We&apos;ll check the shared library before asking for any upload.</p>
                <label className="search-box">
                  <span>⌕</span>
                  <input ref={searchRef} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try “Rice” or “Georgia Tech”" />
                </label>
                <div className="search-results" role="listbox" aria-label="School results">
                  {searchResults.slice(0, 5).map((school) => (
                    <button key={school.id} onClick={() => chooseSchool(school)} role="option" aria-selected="false">
                      <span className="school-avatar" style={{ background: school.color }}>{school.initials}</span>
                      <span><strong>{school.name}</strong><small>{school.location}</small></span>
                      <b className={school.available ? "available-status" : "missing-status"}>{school.available ? "AVAILABLE" : "MISSING"}</b>
                      <em>→</em>
                    </button>
                  ))}
                </div>
              </div>
            ) : null}

            {stage === "available" && candidate ? (
              <div className="modal-content result-stage">
                <div className="big-status available-big">✓</div>
                <span className="modal-kicker success-kicker">CALENDAR AVAILABLE</span>
                <h2 id="modal-title">Good news—someone already added {candidate.shortName}.</h2>
                <p>No upload needed. This reviewed community calendar is ready to attach.</p>
                <div className="calendar-result-card">
                  <span className="school-avatar large-avatar" style={{ background: candidate.color }}>{candidate.initials}</span>
                  <div><strong>{candidate.name}</strong><small>Undergraduate · 2026–2027</small></div>
                  <span className="event-count">{candidate.breaks.length} breaks</span>
                </div>
                <div className="source-line"><span>↗</span><div><b>Source on file</b><small>Sample registrar calendar · reviewed Jul 12</small></div></div>
                <button className="modal-primary" onClick={addAvailableSchool}>Use this calendar <span>→</span></button>
                <button className="modal-back" onClick={() => setStage("search")}>← Search another school</button>
              </div>
            ) : null}

            {stage === "missing" && candidate ? (
              <div className="modal-content result-stage">
                <div className="big-status missing-big">＋</div>
                <span className="modal-kicker missing-kicker">NOT IN THE LIBRARY YET</span>
                <h2 id="modal-title">Be the first to add {candidate.shortName}.</h2>
                <p>For this prototype, use our sample file. A real version would also accept PDFs, screenshots, spreadsheets, text, and .ics files.</p>
                <button className="drop-zone" onClick={simulateUpload}>
                  <span className="upload-arrow">↑</span>
                  <strong>Drop an academic calendar here</strong>
                  <small>or click to use a sample PDF</small>
                  <b>PDF · IMAGE · XLSX · TEXT · ICS</b>
                </button>
                <div className="privacy-note"><span>⌁</span><p><strong>School-wide calendars only</strong><br />Don&apos;t upload a personal class schedule.</p></div>
                <button className="modal-back" onClick={() => setStage("search")}>← Search another school</button>
              </div>
            ) : null}

            {stage === "extracting" ? (
              <div className="modal-content extracting-stage">
                <div className="scan-document">
                  <i className="scan-line" />
                  <span>ACADEMIC CALENDAR</span>
                  <b /><b /><b /><b />
                </div>
                <span className="modal-kicker">READING SAMPLE FILE</span>
                <h2 id="modal-title">Finding dates and breaks…</h2>
                <p>This is simulated in the prototype.</p>
                <div className="loading-track"><i /></div>
              </div>
            ) : null}

            {stage === "review" && candidate ? (
              <div className="modal-content review-stage">
                <span className="modal-kicker">STEP 3 OF 3</span>
                <h2 id="modal-title">Check what we found.</h2>
                <p>Nothing becomes shared until a person confirms it.</p>
                <div className="review-summary"><span>✓</span><strong>{draftEvents.length} no-class periods found</strong><small>From sample-academic-calendar.pdf</small></div>
                <div className="review-list">
                  {draftEvents.map((event) => (
                    <div className="review-row" key={event.id}>
                      <span className="confidence-dot" title="High confidence" />
                      <input aria-label="Event name" value={event.title} onChange={(e) => updateDraft(event.id, "title", e.target.value)} />
                      <label><small>START</small><input type="date" value={event.start} onChange={(e) => updateDraft(event.id, "start", e.target.value)} /></label>
                      <label><small>END</small><input type="date" value={event.end} onChange={(e) => updateDraft(event.id, "end", e.target.value)} /></label>
                    </div>
                  ))}
                </div>
                <label className="confirm-check"><input type="checkbox" defaultChecked /><span>I checked these dates against the source.</span></label>
                <button className="modal-primary" onClick={publishDraft}>Submit for review <span>→</span></button>
                <button className="modal-back" onClick={() => setStage("missing")}>← Back to upload</button>
              </div>
            ) : null}

            {stage === "published" && candidate ? (
              <div className="modal-content published-stage">
                <div className="celebration">✦</div>
                <span className="modal-kicker success-kicker">DEMO REVIEW PASSED</span>
                <h2 id="modal-title">{candidate.shortName} is now reusable.</h2>
                <p>This demo fast-forwards through review. The next student who picks this school and year will see “Calendar available”—no upload required.</p>
                <div className="published-card">
                  <span className="school-avatar large-avatar" style={{ background: candidate.color }}>{candidate.initials}</span>
                  <div><strong>{candidate.shortName} · 2026–27</strong><small>Community calendar · Version 1</small></div>
                  <span>✓</span>
                </div>
                <button className="modal-primary" onClick={closeModal}>See it in the comparison <span>→</span></button>
              </div>
            ) : null}
          </section>
        </div>
      ) : null}
    </main>
  );
}
